version: '3'
services:
  database:
    build:
      dockerfile: db/Dockerfile
    image: todolist-database
    container_name: todolist-db
    restart: always
    volumes:
      - todolist_db:/var/lib/postgresql/data

  server:
    build:
      dockerfile: server/Dockerfile
    image: todolist-server
    container_name: todolist-srv
    restart: on-failure
    ports:
      - 8080:9000
    depends_on:
      - database

  nginx:
    build:
      dockerfile: client/Dockerfile
    container_name: todolist-nginx
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  todolist_db:
