version: '3'
services:
  database:
    build:
      dockerfile: db/Dockerfile
    image: todolist-database
    container_name: todolist-db
    restart: always
    volumes:
      - todolist_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    build:
      dockerfile: src/Dockerfile
    image: todolist-server
    container_name: todolist-srv
    restart: on-failure
    ports:
      - 8080:9000
    depends_on:
      - database

volumes:
  todolist_db:
