@base_url = http://localhost:9000

#Page d''accueil
GET {{base_url}}

###
#Créer une tâche
POST {{base_url}}/tasks
Content-Type: application/json

{
    "content": "mama"
}

###
#Liste des tâches
GET {{base_url}}/tasks

###
#Avoir une certaine tâche
GET {{base_url}}/tasks?id=5

###
#Supprimer une tâche
DELETE  {{base_url}}/tasks/9

###
#Modifier le contenu d'une tâche
PUT {{base_url}}/tasks/12
Content-Type: application/json

{
    "Content": "yo"
}

### Valider/dévalider une tâche
PUT {{base_url}}/tasks/state/145887
