@base_url = http://localhost:9000

#Page d''accueil
GET {{base_url}}

###
#Créer une tâche
POST {{base_url}}/tasks/create/
Content-Type: application/json

{
    "content": "Tatakae"
}

###
#Liste des tâches
GET {{base_url}}/tasks/list/

###
#Supprimer une tâche
DELETE  {{base_url}}/tasks/3