# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build_and_run_api:
    name: Build an Run Go API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version : '1.18'

      # - name: Change directory to server
      #   run: cd server
  
      # - name: Install dependencies
      #   run: go mod download
      
      - name: Unit tests
        run: go test ./server/tests/... -v
  
      - name: Build
        run: go run ./server/main.go &

  test_job_2:
    name: Test Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Run echo command
        run: echo "Running Test Job 2"

  test_job_3:
    name: Test Job 3
    runs-on: ubuntu-latest
    steps:
      - name: Run echo command
        run: echo "Running Test Job 3"
    # steps:
    # - uses: actions/checkout@v3

    # - name: Set up Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version: '1.20'

    # - name: Build
    #   run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...
  
          
